/**
 * The content model, projected into TypeScript.
 *
 * This is what makes `luminx.config.json` the single source of truth for both halves of a project.
 * The CMS gets its sections and fields from the config; the frontend gets its types from the same
 * config. Change a field, and Craft and your Astro components move together — or your build fails,
 * which is the point.
 *
 * It reads the IR, so it knows no CMS, and it reads the *config* rather than a live CMS: types can
 * be generated in CI with no Docker, no PHP and no database. A frontend that cannot typecheck
 * without a running CMS is a frontend that cannot typecheck.
 *
 * Deterministic, like everything else here (§13): same config, same bytes.
 */

import type {
  ContentModel,
  FieldLayoutEntry,
  FieldSpec,
  LogicalId,
  Resource,
} from '@luminx/shared';

/** `heroBlock` → `HeroBlock`. The name a developer will read in their editor. */
const pascal = (handle: string): string =>
  handle
    .replace(/[^a-zA-Z0-9]+(.)?/g, (_match, next: string | undefined) =>
      next === undefined ? '' : next.toUpperCase(),
    )
    .replace(/^(.)/, (first) => first.toUpperCase());

const handleOf = (logicalId: LogicalId): string => logicalId.slice(logicalId.indexOf(':') + 1);

/** A handle that is not a valid TS identifier has to be quoted, and some are (`my-field`). */
const key = (handle: string): string =>
  /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(handle) ? handle : `'${handle}'`;

const quote = (value: string): string => `'${value.replace(/'/g, "\\'")}'`;

/**
 * The shapes a CMS provides rather than the config: an asset is an asset whatever your model says.
 * Deliberately minimal — only what every CMS can honestly promise. An adapter that knows more can
 * widen these later; inventing fields here that some CMS lacks would be a lie in a type.
 */
const PREAMBLE = `/**
 * Generated by LuminX from luminx.config.json. Do not edit.
 *
 * Regenerate with \`luminx types\`. Committing this file is a choice: commit it and your frontend
 * typechecks with no CMS in sight; leave it out and \`luminx types\` becomes a build step.
 */

/** An uploaded file. */
export interface LuminxAsset {
  id: string;
  url: string;
  filename: string;
  title: string | null;
  width: number | null;
  height: number | null;
}

export interface LuminxCategory {
  id: string;
  title: string;
  slug: string;
  uri: string | null;
}

export interface LuminxUser {
  id: string;
  email: string;
  fullName: string | null;
}

export interface LuminxLink {
  url: string;
  label: string | null;
}

export interface LuminxMoney {
  amount: number;
  currency: string;
}

export interface LuminxTableRow {
  [column: string]: string | number | boolean | null;
}

/** What every entry has, whatever its type. */
export interface LuminxEntry {
  id: string;
  title: string;
  slug: string;
  uri: string | null;
}`;

interface Context {
  readonly model: ContentModel;
  /** Entry types reachable from a section, so a matrix block is not also a page. */
  readonly entryTypeNames: ReadonlyMap<LogicalId, string>;
}

/**
 * One field's TypeScript type.
 *
 * A relation whose `maxRelations` is 1 is a single value, not an array — that is the difference
 * between `entry.hero.url` and `entry.hero[0].url`, and getting it wrong is the difference between
 * a type that helps and a type that lies.
 */
const typeOf = (spec: FieldSpec, context: Context): string => {
  const many = (single: string, max: number | undefined): string =>
    max === 1 ? `${single} | null` : `${single}[]`;

  switch (spec.type) {
    case 'text':
    case 'richtext':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'date':
      // ISO 8601. A Date object would be a lie: it arrives from an API as a string.
      return 'string';
    case 'dropdown':
      return spec.options.length === 0
        ? 'string'
        : spec.options.map((option) => quote(option.value)).join(' | ');
    case 'multiselect':
      return spec.options.length === 0
        ? 'string[]'
        : `(${spec.options.map((option) => quote(option.value)).join(' | ')})[]`;
    case 'color':
      return 'string';
    case 'link':
      return 'LuminxLink';
    case 'money':
      return 'LuminxMoney';
    case 'table':
      return 'LuminxTableRow[]';
    case 'assets':
      return many('LuminxAsset', spec.maxRelations);
    case 'categories':
      return many('LuminxCategory', spec.maxRelations);
    case 'users':
      return many('LuminxUser', spec.maxRelations);
    case 'entries': {
      // The sources are sections; an entry from a section is one of that section's entry types.
      const targets = spec.sources.flatMap((source) => {
        const section = context.model.resources.get(source);
        if (section?.kind !== 'section') return [];
        return section.spec.entryTypes.flatMap((id) => context.entryTypeNames.get(id) ?? []);
      });

      const union = targets.length === 0 ? 'LuminxEntry' : [...new Set(targets)].sort().join(' | ');
      return many(targets.length > 1 ? `(${union})` : union, spec.maxRelations);
    }
    case 'matrix': {
      const blocks = spec.entryTypes.flatMap((id) => context.entryTypeNames.get(id) ?? []);
      const union = blocks.length === 0 ? 'never' : [...new Set(blocks)].sort().join(' | ');
      return blocks.length > 1 ? `(${union})[]` : `${union}[]`;
    }
    case 'raw':
      // The escape hatch stays an escape hatch. We never looked inside it; we will not pretend to.
      return 'unknown';
  }
};

/** A layout entry becomes a property: required means non-nullable, and it is per use, not per field. */
const property = (entry: FieldLayoutEntry, context: Context): string => {
  const field = context.model.resources.get(entry.field);
  if (field?.kind !== 'field') return '';

  const type = typeOf(field.spec, context);

  /**
   * Only scalars gain the null.
   *
   * A relation already carries its own (`| null` when `maxRelations` is 1). An array is never
   * null — it is empty. And `unknown` already admits null, so `unknown | null` says nothing extra
   * and reads like a mistake.
   */
  const nullable =
    !entry.required && type !== 'unknown' && !type.endsWith('[]') && !type.endsWith('| null');

  return `  ${key(field.handle)}: ${nullable ? `${type} | null` : type};`;
};

const entryTypeInterface = (resource: Resource, context: Context): string => {
  if (resource.kind !== 'entryType') return '';

  const name = context.entryTypeNames.get(resource.logicalId) ?? pascal(resource.handle);
  const properties = resource.spec.fields
    .map((entry) => property(entry, context))
    .filter((line) => line !== '');

  const body = [
    `  /** The entry type this is, so a union can be narrowed on it. */`,
    `  __typename: ${quote(resource.handle)};`,
    ...properties,
  ].join('\n');

  return `export interface ${name} extends LuminxEntry {\n${body}\n}`;
};

const globalSetInterface = (resource: Resource, context: Context): string => {
  if (resource.kind !== 'globalSet') return '';

  const properties = resource.spec.fields
    .map((entry) => property(entry, context))
    .filter((line) => line !== '');

  return `export interface ${pascal(resource.handle)} {\n${properties.join('\n')}\n}`;
};

export const emitTypes = (model: ContentModel): string => {
  // Sorted, so the same config emits the same bytes (§13).
  const resources = [...model.resources.values()].sort((a, b) =>
    a.logicalId < b.logicalId ? -1 : 1,
  );

  const entryTypes = resources.filter((resource) => resource.kind === 'entryType');
  const globalSets = resources.filter((resource) => resource.kind === 'globalSet');
  const sections = resources.filter((resource) => resource.kind === 'section');

  const entryTypeNames = new Map(
    entryTypes.map((resource) => [resource.logicalId, pascal(resource.handle)]),
  );

  const context: Context = { model, entryTypeNames };

  const blocks: string[] = [PREAMBLE];

  for (const resource of entryTypes) blocks.push(entryTypeInterface(resource, context));
  for (const resource of globalSets) blocks.push(globalSetInterface(resource, context));

  if (sections.length > 0) {
    const entries = sections.map((section) => {
      if (section.kind !== 'section') return '';
      const names = section.spec.entryTypes.flatMap((id) => entryTypeNames.get(id) ?? []).sort();

      const union = names.length === 0 ? 'LuminxEntry' : [...new Set(names)].join(' | ');
      return `  ${key(section.handle)}: ${union};`;
    });

    blocks.push(
      `/** Every section, and the entries it holds. \`LuminxSections['pages']\` is a page. */\nexport interface LuminxSections {\n${entries.join('\n')}\n}`,
    );
  }

  if (globalSets.length > 0) {
    const entries = globalSets.map(
      (resource) => `  ${key(resource.handle)}: ${pascal(resource.handle)};`,
    );
    blocks.push(`export interface LuminxGlobals {\n${entries.join('\n')}\n}`);
  }

  if (entryTypes.length > 0) {
    const union = [...entryTypeNames.values()].sort().join(' | ');
    blocks.push(
      `/** Every entry type in the model. Narrow it on \`__typename\`. */\nexport type LuminxAnyEntry = ${union};`,
    );
  }

  return `${blocks.join('\n\n')}\n`;
};
